/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista.hechoHistorico;

import controlador.ControladorHechos;
import controlador.Utilidades.Utilidades;
import controlador.listas.ListaEnlazada;
import controlador.utililes.FileJSON;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import vista.FrmGrafo;
import vista.hechoHistorico.modeloTabla.ModeloTablaAdyacencia;
import vista.hechoHistorico.modeloTabla.ModeloTablaHechos;
import vista.hechoHistorico.utilidades.Util;

/**
 *
 * @author Usuario
 */
public class FrmHechos extends javax.swing.JFrame {

    ControladorHechos ca = new ControladorHechos();
    ModeloTablaHechos modeloTablaHechos = new ModeloTablaHechos();
    ModeloTablaAdyacencia modeloTablaAdyacencia = new ModeloTablaAdyacencia();
    Integer origen = 0;
    Integer destino = 0;

    /**
     * Creates new form FrmHechos
     */
    public FrmHechos() {
        initComponents();
        panelAdd.setVisible(false);
    }

    public void cargarTabla() {
        if (ca.getListaHechos() != null) {
            modeloTablaHechos.setListaHechos(ca.getListaHechos());
            tablaDocumentos.setModel(modeloTablaHechos);
            tablaDocumentos.updateUI();

        }
    }

    public void cargarCombo() throws Exception {
        Util.cargarComboActividades(cbxOrigen, ca.getListaHechos());
        Util.cargarComboActividades(cbxDestino, ca.getListaHechos());
    }

    public void cargarTablaAdyacencia() {
        try {
            modeloTablaAdyacencia.setGnde(ca.getGnde());
            tablaAdyacencia.setModel(modeloTablaAdyacencia);
            modeloTablaAdyacencia.fireTableStructureChanged();
            tablaAdyacencia.updateUI();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }

    private void fijarAdyacencia() {
        origen = Integer.parseInt(cbxOrigen.getSelectedItem().toString());
        destino = Integer.parseInt(cbxDestino.getSelectedItem().toString());

        if (cbxOrigen.getSelectedItem().equals(cbxDestino.getSelectedItem())) {
            JOptionPane.showMessageDialog(null, "No se debe escoger la misma ubicacion", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                Double tiempo = Util.calcularDiferencia(ca.getListaHechos().obtener((origen) - 1).getAnio_hecho(), ca.getListaHechos().obtener((destino) - 1).getAnio_hecho());
                ca.getGnde().insertarAristaE(ca.getListaHechos().obtener((origen) - 1), ca.getListaHechos().obtener((destino) - 1), tiempo);
                cargarTablaAdyacencia();
                ca.guardarGrafo();
            } catch (Exception e) {
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelAdd = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        txtNombreHe = new javax.swing.JTextField();
        txtAnio = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDocumentos = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        checkAdd = new javax.swing.JCheckBox();
        panelDoc = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cbxDestino = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbxOrigen = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaAdyacencia = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        panelcamino = new javax.swing.JPanel();
        checkFloyd = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        checkDistr = new javax.swing.JCheckBox();
        jButton3 = new javax.swing.JButton();
        panelBusqueda = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        checkAnchura = new javax.swing.JCheckBox();
        checkProfundidad = new javax.swing.JCheckBox();
        jButton4 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtcamino = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(3, 48, 90));

        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hechos Historicos");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(179, 6, 218, 42);

        panelAdd.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("Descripcion:");

        jLabel5.setText("Nombre:");

        jLabel6.setText("Año:");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAddLayout = new javax.swing.GroupLayout(panelAdd);
        panelAdd.setLayout(panelAddLayout);
        panelAddLayout.setHorizontalGroup(
            panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardar)
                    .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtDescripcion)
                        .addComponent(txtNombreHe, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                        .addComponent(txtAnio)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        panelAddLayout.setVerticalGroup(
            panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNombreHe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnGuardar)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel2.add(panelAdd);
        panelAdd.setBounds(10, 50, 270, 150);

        tablaDocumentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaDocumentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaDocumentosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaDocumentos);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(290, 40, 290, 160);

        jButton5.setText("Guardar Json");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(405, 10, 100, 22);

        checkAdd.setText("Añadir Hecho Historico");
        checkAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAddActionPerformed(evt);
            }
        });
        jPanel2.add(checkAdd);
        checkAdd.setBounds(10, 30, 150, 20);

        panelDoc.setPreferredSize(new java.awt.Dimension(550, 350));
        panelDoc.setLayout(null);

        jLabel7.setText("Adyacencia: ");
        panelDoc.add(jLabel7);
        jLabel7.setBounds(6, 6, 67, 16);

        cbxDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelDoc.add(cbxDestino);
        cbxDestino.setBounds(243, 25, 72, 22);

        jLabel8.setText("Origen: ");
        panelDoc.add(jLabel8);
        jLabel8.setBounds(31, 28, 42, 16);

        jLabel9.setText("Destino:");
        panelDoc.add(jLabel9);
        jLabel9.setBounds(194, 28, 43, 16);

        cbxOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelDoc.add(cbxOrigen);
        cbxOrigen.setBounds(79, 25, 72, 22);

        tablaAdyacencia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaAdyacencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaAdyacenciaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaAdyacencia);

        panelDoc.add(jScrollPane2);
        jScrollPane2.setBounds(6, 53, 577, 149);

        jButton1.setText("Ver Grafo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelDoc.add(jButton1);
        jButton1.setBounds(251, 208, 79, 22);

        jButton2.setText("Vincular");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panelDoc.add(jButton2);
        jButton2.setBounds(327, 25, 73, 22);

        panelcamino.setBackground(new java.awt.Color(255, 255, 255));

        checkFloyd.setText("Floyd");
        checkFloyd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkFloydActionPerformed(evt);
            }
        });

        jLabel3.setText("Buscar camino minimo:");

        checkDistr.setText("Distrajk");
        checkDistr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkDistrActionPerformed(evt);
            }
        });

        jButton3.setText("Buscar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelcaminoLayout = new javax.swing.GroupLayout(panelcamino);
        panelcamino.setLayout(panelcaminoLayout);
        panelcaminoLayout.setHorizontalGroup(
            panelcaminoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelcaminoLayout.createSequentialGroup()
                .addGroup(panelcaminoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(panelcaminoLayout.createSequentialGroup()
                        .addGroup(panelcaminoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkFloyd)
                            .addComponent(checkDistr))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelcaminoLayout.setVerticalGroup(
            panelcaminoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelcaminoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGroup(panelcaminoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelcaminoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkFloyd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkDistr))
                    .addGroup(panelcaminoLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButton3)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        panelDoc.add(panelcamino);
        panelcamino.setBounds(6, 248, 146, 100);

        panelBusqueda.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Busqueda:");

        checkAnchura.setText("Anchura");
        checkAnchura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAnchuraActionPerformed(evt);
            }
        });

        checkProfundidad.setText("Profundidad");
        checkProfundidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkProfundidadActionPerformed(evt);
            }
        });

        jButton4.setText("Buscar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBusquedaLayout = new javax.swing.GroupLayout(panelBusqueda);
        panelBusqueda.setLayout(panelBusquedaLayout);
        panelBusquedaLayout.setHorizontalGroup(
            panelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBusquedaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkAnchura)
                    .addComponent(checkProfundidad)))
        );
        panelBusquedaLayout.setVerticalGroup(
            panelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGroup(panelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBusquedaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(checkAnchura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkProfundidad)
                        .addGap(40, 40, 40))
                    .addGroup(panelBusquedaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        panelDoc.add(panelBusqueda);
        panelBusqueda.setBounds(410, 248, 173, 104);

        jScrollPane4.setViewportView(txtcamino);

        panelDoc.add(jScrollPane4);
        jScrollPane4.setBounds(170, 240, 210, 110);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelDoc, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDoc, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 601, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        try {
            // TODO add your handling code here:
            ca.insertarHecho(txtNombreHe.getText(), txtDescripcion.getText(), Integer.parseInt(txtAnio.getText()));
            ca.getListaHechos().imprimir();
            cargarTabla();
            cargarCombo();
        } catch (Exception ex) {
            Logger.getLogger(FrmHechos.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void tablaDocumentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaDocumentosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaDocumentosMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
          new FileJSON("listaActividades").guardar(ca);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tablaAdyacenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaAdyacenciaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaAdyacenciaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            // TODO add your handling code here:
            new FrmGrafo(null, true, ca.getGnde(), 1).setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(FrmHechos.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        fijarAdyacencia();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        if (checkDistr.isSelected()) {
            origen = Integer.parseInt(cbxOrigen.getSelectedItem().toString());
            try {
                ListaEnlazada<Integer> lista = ca.getGnde().Dijkstra(origen);
                lista.imprimir();
                String[] aux = new String[lista.getSize()];
                for (int i = 0; i < lista.getSize(); i++) {
                    aux[i] = ca.getGnde().obtenerEtiqueta(lista.obtener(i)-1).toString();
                }
                txtcamino.setListData(aux);
            } catch (Exception ex) {
                Logger.getLogger(FrmHechos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void checkAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAddActionPerformed
        // TODO add your handling code here:
        if (checkAdd.isSelected()) {
            panelAdd.setVisible(true);
        } else {
            panelAdd.setVisible(false);
        }
    }//GEN-LAST:event_checkAddActionPerformed

    private void checkAnchuraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAnchuraActionPerformed
        // TODO add your handling code here
        if (checkAnchura.isSelected()) {
            panelcamino.setVisible(false);
            checkProfundidad.setVisible(false);
        } else {
            panelcamino.setVisible(true);
            checkProfundidad.setVisible(true);
        }
    }//GEN-LAST:event_checkAnchuraActionPerformed

    private void checkProfundidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkProfundidadActionPerformed
        // TODO add your handling code here:
        if (checkProfundidad.isSelected()) {
            panelcamino.setVisible(false);
            checkAnchura.setVisible(false);
        } else {
            panelcamino.setVisible(true);
            checkAnchura.setVisible(true);
        }
    }//GEN-LAST:event_checkProfundidadActionPerformed

    private void checkFloydActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkFloydActionPerformed
        // TODO add your handling code here:
        if (checkFloyd.isSelected()) {
            panelBusqueda.setVisible(false);
            checkDistr.setVisible(false);
        } else {
            panelBusqueda.setVisible(true);
            checkDistr.setVisible(true);
        }
    }//GEN-LAST:event_checkFloydActionPerformed

    private void checkDistrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkDistrActionPerformed
        // TODO add your handling code here:
        if (checkDistr.isSelected()) {
            panelBusqueda.setVisible(false);
            checkFloyd.setVisible(false);
        } else {
            panelBusqueda.setVisible(true);
            checkFloyd.setVisible(true);
        }
    }//GEN-LAST:event_checkDistrActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (checkAnchura.isSelected()) {
            origen = Integer.parseInt(cbxOrigen.getSelectedItem().toString());
            try {
                Integer[] anchura = ca.getGnde().busquedaAnchura((origen));
                String[] lista = new String[anchura.length];
                for (int i = 0; i < anchura.length; i++) {
                    System.out.println(anchura[i]);
                    lista[i] = ca.getGnde().obtenerEtiqueta((anchura[i])).toString();
                }
                txtcamino.setListData(lista);

            } catch (Exception ex) {
                Logger.getLogger(FrmHechos.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (checkProfundidad.isSelected()) {
            origen = Integer.parseInt(cbxOrigen.getSelectedItem().toString());
            try {
                Integer[] anchura = ca.getGnde().busquedaAnchura((origen));
                String[] lista = new String[anchura.length];
                for (int i = 0; i < anchura.length; i++) {
                    System.out.println(anchura[i]);
                    lista[i] = ca.getGnde().obtenerEtiqueta((anchura[i])).toString();
                }
                txtcamino.setListData(lista);

            } catch (Exception ex) {
                Logger.getLogger(FrmHechos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmHechos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmHechos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmHechos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmHechos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmHechos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbxDestino;
    private javax.swing.JComboBox<String> cbxOrigen;
    private javax.swing.JCheckBox checkAdd;
    private javax.swing.JCheckBox checkAnchura;
    private javax.swing.JCheckBox checkDistr;
    private javax.swing.JCheckBox checkFloyd;
    private javax.swing.JCheckBox checkProfundidad;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel panelAdd;
    private javax.swing.JPanel panelBusqueda;
    private javax.swing.JPanel panelDoc;
    private javax.swing.JPanel panelcamino;
    private javax.swing.JTable tablaAdyacencia;
    private javax.swing.JTable tablaDocumentos;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombreHe;
    private javax.swing.JList<String> txtcamino;
    // End of variables declaration//GEN-END:variables
}
